# Generated by Django 3.1.8 on 2021-10-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211020_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='noTelepon',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
