# Generated by Django 3.1.8 on 2021-10-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211020_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='noTelepon',
            new_name='no_telepon',
        ),
    ]
