# Generated by Django 3.2.7 on 2021-10-22 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_id'),
        ('accounts', '0008_auto_20211020_1225'),
    ]

    operations = [
    ]
