# Generated by Django 3.1.8 on 2021-10-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211020_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='no_telepon',
            field=models.CharField(default='-', max_length=20, unique=True),
        ),
    ]
