# Generated by Django 3.2.9 on 2021-11-30 17:46

import campaigns.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, upload_to=campaigns.utils.campaign_img_upload)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('domicile', models.CharField(max_length=20)),
                ('min_followers', models.IntegerField(default=0)),
                ('desc_photo', models.CharField(max_length=100)),
                ('example_photo', models.ImageField(blank=True, upload_to=campaigns.utils.campaign_img_upload)),
                ('desc_caption', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=50)),
                ('fee', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JoinCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Menunggu Konfirmasi'), (2, 'Lolos Seleksi'), (3, 'Tidak Lolos Seleksi'), (4, 'Task Selesai')], default=1)),
                ('draft', models.ImageField(blank=True, upload_to=campaigns.utils.join_img_upload)),
                ('draft_caption', models.CharField(max_length=1000)),
                ('draft_status', models.PositiveSmallIntegerField(choices=[(1, 'Belum Upload'), (2, 'Baru'), (3, 'Ditolak'), (4, 'Diterima')], default=1)),
                ('post', models.ImageField(blank=True, upload_to=campaigns.utils.join_img_upload)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
        ),
    ]
