# Generated by Django 3.1.8 on 2021-10-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='name',
        ),
        migrations.AddField(
            model_name='campaign',
            name='deskripsi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='judul',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
