# Generated by Django 3.1.8 on 2021-10-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20211020_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='deskripsi',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='judul',
            field=models.CharField(max_length=20),
        ),
    ]
