# Generated by Django 3.1.8 on 2021-10-20 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211020_1225'),
        ('campaigns', '0003_auto_20211020_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.CreateModel(
            name='JoinCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('influenzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.influenzer')),
            ],
        ),
    ]
