# Generated by Django 3.1.8 on 2021-10-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_auto_20211020_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='joincampaign',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Menunggu Konfirmasi'), (2, 'Lolos Seleksi'), (3, 'Tidak Lolos Seleksi'), (4, 'Task Selesai')], null=True),
        ),
    ]
