# Generated by Django 3.1.8 on 2021-10-20 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_auto_20211020_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='joincampaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joincampaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
