# Generated by Django 3.2.7 on 2021-10-22 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_id'),
        ('campaigns', '0010_campaign_lunas'),
    ]

    operations = [
    ]
