# Generated by Django 3.1.8 on 2021-10-21 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_auto_20211020_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joincampaign',
            old_name='influenzer',
            new_name='author',
        ),
    ]
