# Generated by Django 3.1.8 on 2021-10-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_auto_20211021_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='lunas',
            field=models.BooleanField(default=False),
        ),
    ]
