# Generated by Django 3.2.7 on 2021-10-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_merge_0002_alter_campaign_id_0010_campaign_lunas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joincampaign',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
